sudo: true

addons:
  apt:
    sources:
    - sourceline: 'deb http://archive.ubuntu.com/ubuntu trusty-backports main restricted universe multiverse'
    packages:
    - shellcheck

services:
  - docker

before_install:
- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
- sudo apt-get update
- sudo apt-get -y install docker-ce
- docker build -t gluster/client ./gluster-client/
- docker run -it --name client gluster/client rpm -qa | grep gluster
- docker build -t gluster/centos ./CentOS/
- docker run -d --name gcentos --privileged gluster/centos
- sleep 10
- docker exec -it gcentos systemctl is-active glusterd
- docker build -t gluster/fedora ./Fedora/
- docker run -d --name gfedora --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro gluster/fedora
- sleep 10
- docker exec -it gfedora systemctl is-active glusterd
- docker build -t gluster/swift ./gluster-object/CentOS/docker-gluster-swift/
- docker run -d --name swift --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro -e GLUSTER_VOLUMES=vol gluster/swift
- sleep 10
- docker exec -it swift systemctl is-active swift-object

script:
- make test
